# Generated by Django 2.2.2 on 2019-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('preparing', 'preparing'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='ordered', max_length=1)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('margherita', 'margherita'), ('pepperoni', 'pepperoni'), ('mozzarella', 'mozzarella')], max_length=1)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=1)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
